/* QUERYS */

/* Liste todos os carros que est�o com status 'Dispon�vel', mostrando:
marca, modelo, ano e preco */

SELECT MA.NOME,
	   MO.NOME,
	   C.ANO,
	   C.PRECO
FROM CARRO C
INNER JOIN MODELO MO
ON C.ID_MODELO = MO.IDMODELO
INNER JOIN MARCA MA
ON MO.ID_MARCA = MA.IDMARCA
WHERE C.SITUACAO = 'DISPONIVEL'
GO

/* Mostre o nome de todos os clientes que j� realizaram pelo menos uma compra. */

SELECT C.NOME 
FROM CLIENTE C
INNER JOIN VENDAS V
ON V.ID_CLIENTE = C.IDCLIENTE
GO

/* Liste todos os vendedores que ainda n�o realizaram nenhuma venda. */

SELECT IDVENDEDOR, V.NOME
FROM VENDEDOR V 
LEFT JOIN VENDAS VE
ON VE.ID_VENDEDOR = V.IDVENDEDOR
WHERE ID_VENDEDOR IS NULL
GO

/* Exiba o total de carros cadastrados por marca. */

SELECT M.NOME, COUNT(IDCARRO) AS 'QUANTIDADE'
FROM MARCA M
INNER JOIN MODELO MO
ON M.IDMARCA = MO.ID_MARCA
INNER JOIN CARRO C
ON MO.IDMODELO = C.ID_MODELO
GROUP BY(M.NOME)
GO

/* Mostre o valor total vendido por cada vendedor. */

SELECT V.NOME, SUM(VE.VALOR) AS 'VALOR TOTAL VENDIDO'
FROM VENDEDOR V
INNER JOIN VENDAS VE
ON V.IDVENDEDOR	= VE.ID_VENDEDOR
GROUP BY V.NOME
GO

/* Exiba a quantidade de carros vendidos por forma de pagamento.*/

SELECT FP.NOME,COUNT(C.IDCARRO) AS 'QUANTIDADE DE CARROS VENDIDOS'
FROM FORMA_PAGAMENTO FP
INNER JOIN VENDAS VE
ON FP.IDPAGAMENTO = VE.ID_PAGAMENTO
INNER JOIN CARRO C
ON VE.ID_CARRO = C.IDCARRO
GROUP BY FP.NOME
GO

/* Liste os clientes e o valor total gasto por cada um, ordenando do maior para o menor. */

SELECT C.NOME, SUM(V.VALOR) AS 'VALOR TOTAL'
FROM CLIENTE C
INNER JOIN VENDAS V
ON C.IDCLIENTE = V.ID_CLIENTE
GROUP BY C.NOME
ORDER BY [VALOR TOTAL] DESC
GO

/* Mostre o ticket m�dio de venda da concession�ria. */

SELECT AVG(VALOR) AS 'TICKET M�DIO'
FROM VENDAS
GO

/* Liste os carros que nunca foram vendidos. */

SELECT M.NOME 
FROM MODELO M
INNER JOIN CARRO C
ON M.IDMODELO = C.ID_MODELO
LEFT JOIN VENDAS V
ON C.IDCARRO = V.ID_CARRO
WHERE V.ID_CARRO IS NULL
GO


/* Mostre o vendedor que realizou a maior venda individual. */

SELECT TOP 1
    V.NOME AS Vendedor,
    VE.VALOR AS MaiorVenda
FROM VENDAS VE
INNER JOIN VENDEDOR V
    ON VE.ID_VENDEDOR = V.IDVENDEDOR
ORDER BY VE.VALOR DESC;

 /* CRIA��O DE BANCO SO PARA BACKUPS + TABELA BACKUP PARA VENDAS + TRIGGER PARA N�O PERDER HISTORICO DE VENDAS */

CREATE DATABASE BACKUPS
GO

USE BACKUPS

 CREATE TABLE BACKUP_VENDAS(
	IDBACKUP INT PRIMARY KEY IDENTITY,
	DATA_VENDA DATE NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL,
	ID_CLIENTE INT,
	ID_VENDEDOR INT,
	ID_PAGAMENTO INT,
	ID_CARRO INT,
	TIPO_OPERACAO VARCHAR(10) NOT NULL,
	DATA_OPERACAO DATETIME

 )
 GO
 

 CREATE TRIGGER TRG_BACKUP_VENDAS
 ON VENDAS
 AFTER INSERT,DELETE,UPDATE
 AS
 BEGIN
		INSERT INTO BACKUPS.dbo.BACKUP_VENDAS (DATA_VENDA,VALOR,ID_CLIENTE,ID_VENDEDOR,ID_PAGAMENTO,ID_CARRO,
										   TIPO_OPERACAO,DATA_OPERACAO)
		
		SELECT
			I.DATA_VENDA,
			I.VALOR,
			I.ID_CLIENTE,
			I.ID_VENDEDOR,
			I.ID_PAGAMENTO,
			I.ID_CARRO,
			'INSERT',
			GETDATE()
		FROM inserted I

		UNION ALL

		    -- DELETE
    SELECT 
        D.DATA_VENDA,
        D.VALOR,
        D.ID_CLIENTE,
        D.ID_VENDEDOR,
        D.ID_PAGAMENTO,
        D.ID_CARRO,
        'DELETE',
        GETDATE()
    FROM deleted D

	UNION ALL

    -- UPDATE (dados NOVOS)
    SELECT
        I.DATA_VENDA,
        I.VALOR,
        I.ID_CLIENTE,
        I.ID_VENDEDOR,
        I.ID_PAGAMENTO,
        I.ID_CARRO,
        'UPDATE',
        GETDATE()
    FROM inserted I
    INNER JOIN deleted D
        ON I.IDVENDA = D.IDVENDA

END
GO


SELECT *
FROM VENDAS
WHERE IDVENDA = 5
GO

DELETE FROM VENDAS
WHERE IDVENDA = 5
GO

USE BACKUPS

select * from BACKUP_VENDAS
Go

/* PROCEDURE DE FECHAMENTO DE VENDAS */

SELECT * FROM VENDAS
GO

CREATE PROC FECHAMENTO_VENDAS @DATA_VENDA DATE, @VALOR DECIMAL(10,2), @ID_CLIENTE INT,
							  @ID_VENDEDOR INT, @ID_PAGAMENTO INT, @ID_CARRO INT
AS
BEGIN
		SET NOCOUNT ON;

		IF EXISTS( SELECT 1 
			       FROM CARRO
				   WHERE IDCARRO = @ID_CARRO
				   AND SITUACAO = 'VENDIDO')
BEGIN
	RAISERROR('Este carro ja foi vendido',16,1);
	RETURN;
	END

	DECLARE @ID_NOVA_VENDA INT

	INSERT INTO VENDAS(DATA_VENDA,VALOR,ID_CLIENTE,ID_VENDEDOR,ID_PAGAMENTO, ID_CARRO)
				VALUES(@DATA_VENDA,@VALOR,@ID_CLIENTE, @ID_VENDEDOR, @ID_PAGAMENTO, @ID_CARRO)

	SET @ID_NOVA_VENDA = SCOPE_IDENTITY();

	UPDATE CARRO 
	SET SITUACAO = 'VENDIDO'
	WHERE IDCARRO = @ID_CARRO

	SELECT @ID_NOVA_VENDA AS ID_NOVA_VENDA;

END
GO

EXEC FECHAMENTO_VENDAS '2026/02/06',129900.00,3,5,2,15
