/* QUERYS */

/* Listar todos os funcionários com seus cargos */

SELECT F.NOME AS FUNCIONARIO, C.NOME_CARGO AS CARGO
FROM FUNCIONARIO F
INNER JOIN CARGO C
ON F.ID_CARGO = C.IDCARGO
GO

/* Listar funcionários e seus dependentes - mesmo que os que não tenha dependentes */

SELECT F.NOME AS FUNCIONARIOS, D.NOME_DEPENDENTE AS DEPENDENTES, D.PARENTESCO 
FROM FUNCIONARIO F
LEFT JOIN DEPENDENTE D
ON F.IDFUNCIONARIO = D.ID_FUNCIONARIO
GO

/* Quantidade de dependentes por funcionário */

SELECT F.NOME,COUNT(IDDEPENDENTES) AS QTD_DEPENDENTE
FROM FUNCIONARIO F
LEFT JOIN DEPENDENTE D
ON F.IDFUNCIONARIO = D.ID_FUNCIONARIO
GROUP BY NOME
ORDER BY QTD_DEPENDENTE
GO

/* Total de faltas por funcionário */

SELECT F.NOME AS FUNCIONARIOS,COUNT(IDFALTA) AS TOTAL_FALTAS
FROM FUNCIONARIO F
LEFT JOIN FALTA FA
ON F.IDFUNCIONARIO = FA.ID_FUNCIONARIO
GROUP BY F.NOME
GO

/* trazer nome, cargo, departamento, salario atual, total beneficio, qtd faltas */

SELECT 
    F.NOME AS FUNCIONARIO,
    C.NOME_CARGO AS CARGO,
    D.NOME_DEPART AS DEPARTAMENTO,
    S.VALOR AS SALARIO_ATUAL,
    ISNULL(B.TOTAL_BENEFICIO, 0) AS TOTAL_BENEFICIO,
    ISNULL(FA.TOTAL_FALTA, 0) AS TOTAL_FALTA
FROM FUNCIONARIO F
INNER JOIN CARGO C
    ON F.ID_CARGO = C.IDCARGO
INNER JOIN DEPARTAMENTO D
    ON F.ID_DEPARTAMENTO = D.IDDEPARTAMENTO
INNER JOIN SALARIO S
    ON F.IDFUNCIONARIO = S.ID_FUNCIONARIO
    AND S.DATA_FIM IS NULL

LEFT JOIN (
    SELECT 
        ID_FUNCIONARIO,
        SUM(VALOR) AS TOTAL_BENEFICIO
    FROM FUNCIONARIO_BENEFICIO
    WHERE DATA_FIM IS NULL
    GROUP BY ID_FUNCIONARIO
) B 
    ON F.IDFUNCIONARIO = B.ID_FUNCIONARIO


LEFT JOIN (
    SELECT 
        ID_FUNCIONARIO,
        COUNT(*) AS TOTAL_FALTA
    FROM FALTA
    GROUP BY ID_FUNCIONARIO
) FA 
    ON F.IDFUNCIONARIO = FA.ID_FUNCIONARIO

ORDER BY TOTAL_BENEFICIO DESC, TOTAL_FALTA DESC
GO

/* CLASSIFICAÇÃO SALARIAL / CLASSIFICAÇÃO DE FALTAS */

SELECT F.NOME AS FUNCIONARIOS,S.VALOR AS SALARIO_ATUAL, COUNT(FA.IDFALTA) AS TOTAL_FALTAS,
	   CASE
			WHEN S.VALOR < 3000 THEN 'BAIXO'
			WHEN S.VALOR <= 7000 THEN 'MÉDIO'
			ELSE 'ALTO'
		END AS CLASSIFICAÇÃO_SALARIAL,
		CASE
			WHEN COUNT(FA.IDFALTA) = 0 THEN 'EXCELENTE'
			WHEN COUNT(FA.IDFALTA) <= 3 THEN 'ATENÇÃO'
			WHEN COUNT(FA.IDFALTA) > 3 THEN 'CRÍTICO'
		END AS CLASSIFICAÇÃO_FALTAS
FROM FUNCIONARIO F
INNER JOIN SALARIO S
ON F.IDFUNCIONARIO = S.ID_FUNCIONARIO
AND DATA_FIM IS NULL
LEFT JOIN FALTA FA
ON F.IDFUNCIONARIO = FA.ID_FUNCIONARIO
GROUP BY F.NOME,S.VALOR
ORDER BY TOTAL_FALTAS ASC
GO

/* UTILIZANDO CTE PARA CLASSIFICAÇÃO DE FUNCIONARIOS*/

WITH DADOS_FUNCIONARIOS AS(
	SELECT F.NOME AS FUNCIONARIO,
		   C.NOME_CARGO AS CARGO,
		   S.VALOR AS SALARIO_ATUAL,
		   COUNT(FA.IDFALTA) AS TOTAL_FALTA
	FROM FUNCIONARIO F
	INNER JOIN CARGO C
	ON F.ID_CARGO = C.IDCARGO
	INNER JOIN SALARIO S
	ON F.IDFUNCIONARIO = S.ID_FUNCIONARIO
	AND DATA_FIM IS NULL
	LEFT JOIN FALTA FA
	ON F.IDFUNCIONARIO = FA.ID_FUNCIONARIO
	GROUP BY F.NOME,C.NOME_CARGO,S.VALOR
)

SELECT FUNCIONARIO,
	   CARGO,
	   SALARIO_ATUAL,
	   TOTAL_FALTA,
	   CASE
			WHEN SALARIO_ATUAL <= 3000 THEN 'BAIXO'
			WHEN SALARIO_ATUAL <= 6000 THEN 'MÉDIO'
			ELSE 'ALTO'
	   END AS CLASSIFICACAO
INTO #RELATORIO_FUNCIONARIO -- INSERINDO OS DADOS EM UMA TABELA TEMPORARIA
FROM DADOS_FUNCIONARIOS
GO

SELECT * FROM #RELATORIO_FUNCIONARIO
WHERE CLASSIFICACAO = 'ALTO'
GO

/* Total de benefícios por funcionário
Soma dos valores*/

WITH DADOS_BENEFICIOS AS(
	SELECT F.NOME,
		   (FB.ID_BENEFICIO) AS TOTAL_BENEFICIO,
		   SUM(FB.VALOR) VALOR_TOTAL
	FROM FUNCIONARIO F
	INNER JOIN FUNCIONARIO_BENEFICIO FB
	ON F.IDFUNCIONARIO = FB.ID_FUNCIONARIO
	GROUP BY F.NOME

)

SELECT NOME,
	   TOTAL_BENEFICIO,
	   VALOR_TOTAL
FROM DADOS_BENEFICIOS
WHERE VALOR_TOTAL > 200
GO

/* PROCEDURES */

/* Procedure: Admitir funcionário*/

CREATE PROCEDURE ADMITIR_FUNC
	   @NOME VARCHAR(50),
	   @CPF VARCHAR(15),
	   @SEXO CHAR(1),
	   @DATA_NASCIMENTO DATE,
	   @EMAIL VARCHAR(50),
	   @STATUS VARCHAR(10),
	   @ID_CARGO INT,
	   @ID_DEPARTAMENTO INT,
	   @SALARIO DECIMAL(10,2),
	   @CIDADE VARCHAR(50),
	   @DATA_DEMISSAO DATE

AS
BEGIN
		INSERT INTO FUNCIONARIO(NOME,CPF,SEXO,DATA_NASCIMENTO,DATA_ADMISSAO,EMAIL,STATUS,ID_CARGO,ID_DEPARTAMENTO,CIDADE,DATA_DEMISSAO) 
		VALUES (@NOME,@CPF,@SEXO,@DATA_NASCIMENTO,GETDATE(),@EMAIL,@STATUS,@ID_CARGO,@ID_DEPARTAMENTO,@CIDADE,@DATA_DEMISSAO)

		DECLARE @ID_FUNC INT = SCOPE_IDENTITY()

		INSERT INTO SALARIO(DATA_INICIO,VALOR,ID_FUNCIONARIO)
		VALUES (GETDATE(),@SALARIO,@ID_FUNC)
END
GO



EXEC ADMITIR_FUNC 'Marcos Vinícius Alcantara','4453245676','M','2002-02-20','marcosvini@gmail.com','Ativo',5,1,4000.00
GO

EXEC ADMITIR_FUNC 'Julio Fernandes Lima','4653895676','M','2002-05-20','juliofern@gmail.com','Ativo',4,2,3000.00
GO

/* INSERTS VIA PROCEDURE - NOVOS FUNCIONÁRIOS (ID 16 AO 20) */




SELECT * FROM SALARIO

SELECT * FROM FUNCIONARIO

/*  Procedure de Atualizar salário (histórico) */

CREATE PROCEDURE ATUALIZAR_SALARIO
	   @ID_FUNCIONARIO INT,
	   @NOVO_SALARIO DECIMAL(10,2)
AS
BEGIN
		UPDATE SALARIO
		SET DATA_FIM = GETDATE()
		WHERE ID_FUNCIONARIO = @ID_FUNCIONARIO
		AND DATA_FIM IS NULL
	    
		INSERT INTO SALARIO (DATA_INICIO,VALOR,ID_FUNCIONARIO)
		VALUES ( GETDATE(),@NOVO_SALARIO,@ID_FUNCIONARIO)
END
GO

EXEC ATUALIZAR_SALARIO 11,2800.00


/* PROCEDURE DE REGISTRAR FALTA */

CREATE PROCEDURE REGISTRAR_FALTA
	   @ID_FUNCIONARIO INT,
	   @MOTIVO VARCHAR(50)
AS
BEGIN
		INSERT INTO FALTA (MOTIVO,DATA_FALTA,ID_FUNCIONARIO)
		VALUES (@MOTIVO,GETDATE(),@ID_FUNCIONARIO)
END
GO

EXEC REGISTRAR_FALTA 1,'Consulta médica'

/* SUBQUERYS */

/* 1. Funcionários acima da média salarial */

SELECT F.NOME AS FUNCIONARIO, S.VALOR AS SALARIO
FROM FUNCIONARIO F
INNER JOIN SALARIO S
ON F.IDFUNCIONARIO = S.ID_FUNCIONARIO
WHERE VALOR > ( SELECT AVG(VALOR) AS MEDIA_SALARIAL
				FROM SALARIO
				WHERE DATA_FIM IS NULL)
GO

/*2. Funcionário com maior salário*/


SELECT NOME, VALOR AS MAIOR_SALARIO
FROM FUNCIONARIO
INNER JOIN SALARIO
ON IDFUNCIONARIO = ID_FUNCIONARIO
WHERE VALOR = (SELECT MAX(VALOR)
			   FROM SALARIO
			   WHERE DATA_FIM IS NULL)
GROUP BY NOME,VALOR
GO

/* 3. Funcionários com mais faltas que a média */

SELECT 
    F.NOME,
    COUNT(FA.IDFALTA) AS TOTAL_FALTAS
FROM FUNCIONARIO F
LEFT JOIN FALTA FA
    ON F.IDFUNCIONARIO = FA.ID_FUNCIONARIO
GROUP BY F.NOME
HAVING COUNT(FA.IDFALTA) > (
    SELECT AVG(QTD_FALTAS)
    FROM (
        SELECT COUNT(*) AS QTD_FALTAS
        FROM FALTA
        GROUP BY ID_FUNCIONARIO
    ) AS MEDIA
)

/* Funcionários com salário acima de 5000 */

WITH SALARIO_ATUAL AS (
	SELECT F.NOME AS FUNCIONARIO,S.VALOR AS SALARIO_ATUAL
	FROM FUNCIONARIO F
	INNER JOIN SALARIO S
	ON F.IDFUNCIONARIO = S.ID_FUNCIONARIO
	WHERE DATA_FIM IS NULL
	GROUP BY F.NOME, S.VALOR

)

SELECT FUNCIONARIO,SALARIO_ATUAL
FROM SALARIO_ATUAL
WHERE SALARIO_ATUAL > 5000
ORDER BY SALARIO_ATUAL DESC
GO

/* FUNCIONARIO SEM DEPENDENTE */

WITH TOTAL_DEPENDENTE AS(
	SELECT ID_FUNCIONARIO, COUNT(*) AS QTD_DEPENDENTES
	FROM DEPENDENTE
	GROUP BY ID_FUNCIONARIO


)

SELECT F.NOME
FROM FUNCIONARIO F
LEFT JOIN TOTAL_DEPENDENTE TD
ON F.IDFUNCIONARIO = TD.ID_FUNCIONARIO
WHERE TD.QTD_DEPENDENTES IS NULL
GO

/* CTE QUE MOSTRE NOME,CARGO E SALARIO 
ATUAL E DEPOIS TRAZER FUNCIONARIOS QUE GANHAM MAIS DE 4K */

WITH FUNCIONARIO_INFO AS(
	SELECT F.NOME AS FUNCIONARIO,C.NOME_CARGO AS CARGO,S.VALOR AS SALARIO
	FROM FUNCIONARIO F
	INNER JOIN CARGO C
	ON F.ID_CARGO = C.IDCARGO
	INNER JOIN SALARIO S
	ON F.IDFUNCIONARIO = S.ID_FUNCIONARIO
	WHERE S.DATA_FIM IS NULL

)

SELECT FUNCIONARIO, CARGO, SALARIO
FROM FUNCIONARIO_INFO
WHERE SALARIO > 4000
GROUP BY FUNCIONARIO, CARGO, SALARIO
GO

/* CTE PARA QUANTIDADE DE FALTAS POR FUNCIONARIO
E DEPOIS TRAGA FUNCIONARIOS COM MAIS DE 3 FALTAS */

WITH QTD_FALTAS AS(
	SELECT F.NOME AS FUNCIONARIO, COUNT(ID_FUNCIONARIO) AS QTD_FALTA
	FROM FUNCIONARIO F
	LEFT JOIN FALTA FA
	ON F.IDFUNCIONARIO = FA.ID_FUNCIONARIO
	GROUP BY F.NOME

)

SELECT FUNCIONARIO,QTD_FALTA
FROM QTD_FALTAS
WHERE QTD_FALTA > 1
GO

/* Liste os funcionários que possuem: 
salário acima da média salarial da empresa */

SELECT F.NOME AS FUNCIONARIO
FROM FUNCIONARIO F
INNER JOIN SALARIO S
ON F.IDFUNCIONARIO = S.ID_FUNCIONARIO
WHERE S.DATA_FIM IS NULL AND S.VALOR  > (SELECT AVG(VALOR) FROM SALARIO WHERE DATA_FIM IS NULL)
GROUP BY F.NOME
GO

/* MOSTRE O FUNCIONARIO COM MAIOR SALARIO ATUAL */

SELECT NOME, VALOR
FROM FUNCIONARIO F
INNER JOIN SALARIO S
ON F.IDFUNCIONARIO = S.ID_FUNCIONARIO
WHERE VALOR = (SELECT MAX(VALOR) FROM SALARIO WHERE DATA_FIM IS NULL)
GO

/* Liste funcionários que:
possuem mais faltas do que a média de faltas da empresa. */

SELECT F.NOME AS FUNCIONARIO
FROM FUNCIONARIO F
LEFT JOIN FALTA FA
ON F.IDFUNCIONARIO = FA.ID_FUNCIONARIO
GROUP BY F.NOME
HAVING COUNT(FA.IDFALTA) > ( SELECT AVG(QTD_FALTAS)
									FROM ( SELECT COUNT(*) AS QTD_FALTAS
										   FROM FALTA
										   GROUP BY ID_FUNCIONARIO)
										   AS MEDIA_FALTA
)										   							
GO

/* Crie uma CTE com: Nome, Departamento, Salário atual
Depois: Mostre apenas o maior salário de cada departamento. */

WITH FUNCIO_INFO AS(
SELECT F.NOME AS FUNCIONARIO, D.NOME_DEPART AS DEPARTAMENTO, S.VALOR AS SALARIO_ATUAL
FROM FUNCIONARIO F
INNER JOIN DEPARTAMENTO D
ON F.ID_DEPARTAMENTO = D.IDDEPARTAMENTO
INNER JOIN SALARIO S
ON F.IDFUNCIONARIO = S.ID_FUNCIONARIO
WHERE S.DATA_FIM IS NULL

)

SELECT DEPARTAMENTO,MAX(SALARIO_ATUAL) AS MAIOR_SALARIO
FROM FUNCIO_INFO
GROUP BY DEPARTAMENTO
GO

